services:
  trainer-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlops-trainer-worker
    env_file:
      - .env
    command: ["uv", "run", "python", "-m", "src.train.run_train"]
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlops-api
    env_file:
      - .env
    command: ["uv", "run", "uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    restart: unless-stopped
