FROM apache/airflow:2.10.2-python3.11

USER airflow
RUN pip install --no-cache-dir \
    "boto3>=1.37.0" \
    "numpy>=2.2.0" \
    "pandas>=2.2.0" \
    "pydantic-settings>=2.7.0" \
    "pymysql>=1.1.0" \
    "scikit-learn>=1.6.0" \
    "sqlalchemy<2" \
    "torch>=2.6.0" \
    "tqdm>=4.67.0" \
    "wandb>=0.19.0"
